### ISSUE TITLE
invalid JSON 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#1]
https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/models/result_WGS84.json 

```
{
"mode": [1,people],
"path": [[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395],
[2.310857774689342, 48.86936569737395]
],
"timestamps": [0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0
]
},

``` 
`people` is invalid notation

**Comment by RELNO** [comment]
As well, timestamps should be `INT` and should not all be the same

**Comment by agrignard** [comment]
Ok for the time it was an issue due to the conversion to WGS86 (the Z was lost) so now I just push the 10 first cyle but we can change that.

Then what's the problem for ```people```?  You need a string ?

**Comment by RELNO** [comment]
I don't need Z, so keep lat long as is. The two things to change : people (or any string) must be "string" and timestamp must be integers. 
Lastly, create a longer simulation so I can improve my calibration of 3d model to sim

**Comment by agrignard** [comment]
Should be fixed now 

- people is a string 

- loc is an int (however I think three.js should be able to deal either with int or float (can't you cast it? cityScopeJS is accepting a float no?

I only put 50 values for now (representing 50x2.5sec) but we can put more ones it's working

**Comment by RELNO** [comment]
I can't find the JSON, did you pushed it somewhere else? 

> loc is an int (however I think three.js should be able to deal either with int or float (can't you cast it? cityScopeJS is accepting a float no?

What is loc? What needs to be `int` is timestamp. This is not because we cannot cast `float` -> `int` but b/c the schema for this data should be using timestamps of seconds. Floats of seconds make less sense (milliseconds ?)

**Comment by agrignard** [comment]
sorry not loc, timestamp.

I think it can make sense to have something like 1.2 sec (for instance to replay other simulation (not about human but faster process) but anyway for this it's not a big deal an int is enough and can actually save space

**Comment by RELNO** [comment]
The issue with timestamps in float is that the tick of simulation function runs integer intervals [0,1,2....n]
So if we use non `int` values, it's not easy to match the sim tick to the time without slowing down the sim quite significantly => 1.2 * 10 = 12

**Comment by RELNO** [comment]
https://github.com/CityScope/CSL_Paris/commit/2688ba9194bf4643376f7a61f1088557de824331 closes this. Still require larger JSON for alignments
