### ISSUE TITLE
Parks, cultural Shapefiles are in different scale / projection

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#12]
in the context of #6, the SHP files exported with parks, culture etc are in odd scale/projection. It look like they are scaled into the table scale **which should not be done outside of THREE**. Instead, these should be exported as the building layer was exported in `Champ_GIS_buildings` folder

**Comment by RELNO** [comment]
![Screen Shot 2020-04-03 at 15 59 22](https://user-images.githubusercontent.com/14296774/78400386-990c9580-75c4-11ea-8388-c0ffa9fbcf45.png)

**Comment by agrignard** [comment]
they are in WGS 84 but I can put them like the building so in lambert93 is this ok?

**Comment by RELNO** [comment]
we can try, but is there also scaling involved?

**Comment by agrignard** [comment]
no there is no scaling here it's pure .shp i just pushed with the lambert93 (same as building)

**Comment by RELNO** [comment]
ok cool let's go with the right projection and see.

**Comment by agrignard** [comment]
I think this one is fixed? @RELNO I let you reopen this issue if it's not the case
