### ISSUE TITLE
Radar Plot Integration

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#13]
Integrate the Radar Plot.

There is 2 .Png representing the radar plot before and after here
https://github.com/CityScope/CSL_Paris/tree/master/ReChamp_Gama/includes/PNG/radar_plot
(001.jpeg and 002.jpeg)

In the ream room the Radar Plot (somethin like 3mx2m) are projected on the wall on the north side of the table

**Comment by LAAP** [comment]
How are we going to Show the radar in the virtual world? Maybe emerges only when exploring the table?

**Comment by agrignard** [comment]
@RELNO was also suggesting this, like on top of the table you mean? there also the option to have a kind of transparent wall. I can see if I can refind the AI file I think Nico might have it?

**Comment by RELNO** [comment]
Radar plot should be recreated in English in a Illustrator / vector. There's no need to export the bar graphs. @nayoub @LAAP can you please help with this? 

![1](https://user-images.githubusercontent.com/14296774/79066033-ae4b8900-7c82-11ea-9fd3-413f905d02c0.jpg)

**Comment by agrignard** [comment]
Also I know it's WIP but  just to remind to have the before and the after, when toggling 2020-2040

**Comment by nayoub** [comment]
Sure, I can do an English version. @RELNO do you need an SVG file for the output?

**Comment by RELNO** [comment]
Great thanks -- would be good to have the .ai so I could quickly iterate on line weights

**Comment by LAAP** [comment]
Thanks @nayoub !

**Comment by RELNO** [comment]
@nayoub  @LAAP  to do: 
- make before after radar in english 
- make highlighted radar for each segment (the change in cars/parks/cultures/ etc..)

clean up and make more readable

**Comment by LAAP** [comment]
We can do this, @nayoub Let's coordinate

@RELNO , the 2nd point. "make highlighted radar for each segment (the change in cars/parks/cultures/ etc..)"
Not sure if we are talking about:

A- Making specific radar per segment (not sure yet how to do it: Energy bar, or similar),

B - or showing how the radar is changing (growing or shrinking) in each segment, one by one... Kind of a GIF image

**Comment by RELNO** [comment]
@LAAP  most likely B -- the idea is that we can show the specific impact of a layer on a certain segment of the radar -- so if you toggle the cars, only cars-related radar edges/nodes are highlighted.

**Comment by LAAP** [comment]
Ok. Makes sense. So all the rest axes are staying as it is today, and we only show the spike that is changing when we toggle it. 
@nayoub , can you share with me the last Ps version? I can do all of this

**Comment by RELNO** [comment]
for @RELNO records: https://stackoverflow.com/questions/45761324/animate-between-two-materials-on-a-mesh-three-js

**Comment by nayoub** [comment]
Ok noted, thanks! @LAAP I can send you the illustrator file, but I need to make a few adjustments first

**Comment by RELNO** [comment]
@nayoub please make sure to keep square aspect ratio, similar to 

> ![1](https://user-images.githubusercontent.com/14296774/79066033-ae4b8900-7c82-11ea-9fd3-413f905d02c0.jpg)

**Comment by nayoub** [comment]
Sure, I will keep the same artboard. Do we still have our call at 10?

**Comment by RELNO** [comment]
Yes. 10ish ¯\_(ツ)_/¯

**Comment by LAAP** [comment]
Awesome @nayoub !

**Comment by nayoub** [comment]
@RELNO committed an english version of the before/after just for first implementation.
Sorry forgot to PR. You'll find .ai + jpg exports in the radar folder in textures.
Let me know if anything should be changed before we export the other ones (cars, pedestrian, nature, etc).

**Comment by RELNO** [comment]
@nayoub I see a revert on your commit, are you still working on it?

**Comment by nayoub** [comment]
No the revert was to PR but it removed the files on my mac so I re-reverted ;)

**Comment by RELNO** [comment]
@LAAP can you share the numerical values of change for each of the 5 categories? 
![Screen Shot 2020-04-18 at 16 13 31](https://user-images.githubusercontent.com/14296774/79670245-9054bb80-818f-11ea-861a-0ca33fde5f2e.png)

**Comment by RELNO** [comment]
closing on https://github.com/CityScope/CSL_Paris/commit/5aafb86ba0230839ffaf64dadc73f5d16d4cea09

**Comment by LAAP** [comment]
Hi Guys I am reopening this issue: @RELNO @agrignard @nayoub, I have made an iteration with the potential rada per "tag". Please, let me know your thoughts:

1) Cars 2020-2040: 

![Radar_Plot_EN-CAR2020](https://user-images.githubusercontent.com/19315213/79811855-21b95e80-8345-11ea-9796-ddfccad9f5d4.jpg)

![Radar_Plot_EN-CAR2040](https://user-images.githubusercontent.com/19315213/79811889-40b7f080-8345-11ea-94cf-7f312c8406a0.jpg)

2) Bike 2020-2040: 

![Radar_Plot_EN-bike2020](https://user-images.githubusercontent.com/19315213/79811928-5a593800-8345-11ea-9b7b-d8e822409885.jpg)


![Radar_Plot_EN-bike2040](https://user-images.githubusercontent.com/19315213/79811934-62b17300-8345-11ea-8574-65b5fa396bf5.jpg)

3) Leisure 2020-2040: 

![Radar_Plot_EN-Leisure2020 copia](https://user-images.githubusercontent.com/19315213/79811959-75c44300-8345-11ea-957c-94efc92ebdb5.jpg)

![Radar_Plot_EN-Leisure2040](https://user-images.githubusercontent.com/19315213/79811976-7eb51480-8345-11ea-8ea3-6ada61bbc660.jpg)

4) Parks 2020-2040: 

![Radar_Plot_EN-PARK2020 copia](https://user-images.githubusercontent.com/19315213/79811994-8c6a9a00-8345-11ea-8c75-fb3bb8314186.jpg)

![Radar_Plot_EN-Park2040](https://user-images.githubusercontent.com/19315213/79812012-97252f00-8345-11ea-928f-f219b2b23401.jpg)

5) Pedestrian 2020-2040: 

![Radar_Plot_EN-Pedestrian2020](https://user-images.githubusercontent.com/19315213/79812027-a1472d80-8345-11ea-827f-1ec8d65fd403.jpg)

![Radar_Plot_EN-Pedestrians2040](https://user-images.githubusercontent.com/19315213/79812054-b9b74800-8345-11ea-8551-5210044008e3.jpg)

**Comment by agrignard** [comment]
@LAAP I am afraid you are not using the right radar... See issue #38

**Comment by LAAP** [comment]
@agrignard , as commented in issue [#38](https://github.com/CityScope/CSL_Paris/issues/38), I am using the english version:

https://github.com/CityScope/CSL_Paris/blob/master/champscope/public/resources/textures/radar/Radar_Plot_EN.ai

In any case, please, can you tell me your opinion about the radars? Should I keep working on it as soon as @nayoub fixes the English version of the radar or not?

**Comment by nayoub** [comment]
@LAAP I just pushed the good one, I commented on issue #38. So sorry about that.

**Comment by LAAP** [comment]
Thanks @nayoub!
To @all , Should I update this radars or not?

**Comment by agrignard** [comment]
I don't understand what you mean by update (you mean with different color per mode)? And to be hosnest I am a bit lost in the different version of radar and I lost a bit track of the integration. I see different radar in the issues and in the working version. 

This
<img width="884" alt="Screen Shot 2020-04-21 at 17 07 27" src="https://user-images.githubusercontent.com/3928502/79882331-b29a4380-83f2-11ea-9eb3-6e14bb3d45e4.png">
 is what I see currently in the website (who produced them?)
<img width="872" alt="Screen Shot 2020-04-21 at 17 07 34" src="https://user-images.githubusercontent.com/3928502/79882307-aa420880-83f2-11ea-8da3-6e84ae68ace5.png">



To me the me the priority is more this https://github.com/CityScope/CSL_Paris/issues/29 than changing the radar. 

I would say if you think the radar as they are are not good then yes it needs to be updated otherwise I don't understand what you mean by update

**Comment by LAAP** [comment]
Hi @agrignard , 

Regarding Issue [#29](https://github.com/CityScope/CSL_Paris/issues/29), I think that it "is closed", but @RELNO wants to keep it open just in case. I have already answer to your questions, however, please, let me know if you have any further question.

Update in the Radar is: 
1- @nayoub has made a translation to English (it is in ReChamp. @nayoub , can you move it to CSL_Paris, please?

 2- As commented, last day, I have made a test of the "tag radars" related to cars, bike, etc. (from **this repo #13**). The radar used was an **"old EN version" at ReChamp**, but It can be very fast to shift into the new version. I am just waiting from you to say **YES** or **NOT**

3-The two images from your comment (2h ago) above, are made by Ariel. And I can tell that he is also using the **"old EN version" at ReChamp**.

So, if we agree, @nayoub can move the **"New EN version" to CSL_Paris**, and you can give me the **Go!** or **Not go!** on the "tag radars"

**Comment by nayoub** [comment]
**Just to confirm:** 
The last version of the Illustrator file is **Radar_Plot_EN_Expo.ai**, it was pushed 2hours ago.
But I always pushed in CSL_Paris, technically nothing should be in ReChamp (as the folder "champscope" doesn't even exist on that repo).
I can also make any adjustments if needed :)

**Comment by agrignard** [comment]
For this one https://github.com/CityScope/CSL_Paris/issues/29 I don't think it's closed. I don't see the text when we change the layer.

For the tag I let you decide it might involved some extra work to integrate it so up to you

**Comment by LAAP** [comment]
Thank you very much @nayoub , I don't get either the confusion with repos, but it was pointed by @agrignard in a whatsapp, so I have added here. I am following you, and I am not even pushing anything yet.

To @ALL, If you are not interested in "tag radars" that is fantastic, so I can move into other things

**Comment by RELNO** [comment]
thanks all! closing
