### ISSUE TITLE
Z buffer fighting with different plane

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#16]
A common hard to solve a problem in OpenGL due to z-buffer and shape drawn on the same z-plane.
What about slightly changing the z value for park and make them a bit higher? It should do the trick?

<img width="865" alt="Screen Shot 2020-04-08 at 15 34 49" src="https://user-images.githubusercontent.com/3928502/78790270-91773300-79ae-11ea-94af-b7f8ed40b852.png">

**Comment by RELNO** [comment]
Culture and parks are already in different z heights. The z of old parks vs new parks is still the same but could be changed

**Comment by agrignard** [comment]
yes just the light green park a bit higher

**Comment by agrignard** [comment]
Seems to be fix for park and cultural but seems to appears with agent  on parks
<img width="207" alt="Screen Shot 2020-04-10 at 12 48 09" src="https://user-images.githubusercontent.com/3928502/78985754-d8d5fe80-7b29-11ea-99a0-8a3c6c4a606a.png">

**Comment by RELNO** [comment]
can you try and export all (city model, park, culture) at the same scale in either obj or gltf?  other possible import formats https://threejs.org/docs/#manual/en/introduction/Loading-3D-models

**Comment by agrignard** [comment]
You mean for this specific issue or for a more general one ? The original one are all in shapefile format. (.shp or geojson) and the 3D model has been creating from this.

However I don't knwo which 3D model (city) you are actually using and what is the conversion process from the shp (park, culture) to the 3D object

**Comment by RELNO** [comment]
so going back to what ( i hoped) would be a simple process became complex since exporting the city model from shp => three js is impossible with a corrupted shp file.
Qgis has a very simple plugin that does that exactly: https://plugins.qgis.org/plugins/Qgis2threejs/
However, the city model (buildings layer) is a mess and crashes the plug in and qgis when trying to export. So now, I'm forced to export each layer in a different way which ends up requiring hours of tiny adjustments to align. 
What I need: 5 objects (city, parks b /parks a, culture b /culture a) in OBJ/GLTF format, **which are all exported  the same way**.

**Comment by RELNO** [comment]
BTW at this point it might be simpler to ask PCA for their rhino/3d max model and use that.

**Comment by RELNO** [comment]
![Screen Shot 2020-04-10 at 11 55 32](https://user-images.githubusercontent.com/14296774/79004178-36664d00-7b22-11ea-9c81-b523bdc85d5e.png)
as an example, when selecting few buildings from that layer (here in purple) , the plugin has no issue. But some building/s (out of ~7000) are corrupted.

**Comment by agrignard** [comment]
ok let me see with @tnguyenh if we can export this in .obj from blender

**Comment by tnguyenh** [comment]
Try the buildings.obj that I just pushed

**Comment by RELNO** [comment]
![Screen Shot 2020-04-10 at 18 28 34](https://user-images.githubusercontent.com/14296774/79027164-32a1ed00-7b59-11ea-9e64-a124207ef14a.png)

@tnguyenh thanks for helping with this -- what is the process you use for shp=>obj? 
In the culture it looks like the Champs objects got offsetted

**Comment by agrignard** [comment]
we use blender and we put an arbitrary depth for all the building, it's possible if needed with a bit of work to put the exact height

**Comment by RELNO** [comment]
I don't talk about height, see the buildings on the main street, they are supposed to be straight no?
In blender, what is the process?  
If you use this importer you'll soon see that convexes and holed objects are imported as separated objects so that you'd have to boolean by hand   
![Screen Shot 2020-04-10 at 18 38 19](https://user-images.githubusercontent.com/14296774/79027501-777a5380-7b5a-11ea-8002-7332570f8926.png)

**Comment by agrignard** [comment]
"see the buildings on the main street, they are supposed to be straight no?" => which one?

**Comment by agrignard** [comment]
https://github.com/CityScope/CSL_Paris/issues/18#issuecomment-612238635

**Comment by RELNO** [comment]
> "see the buildings on the main street, they are supposed to be straight no?" => which one?

in this image https://github.com/CityScope/CSL_Paris/issues/16#issuecomment-612246617
I've tested Tri's OBJ and it rendered the cultural objs in odd diagonal.

**Comment by tnguyenh** [comment]
Why by hand ? Try the new buildings.obj.

**Comment by tnguyenh** [comment]
still a few errors on some faces, working on it.

**Comment by agrignard** [comment]
> > "see the buildings on the main street, they are supposed to be straight no?" => which one?
> 
> in this image [#16 (comment)](https://github.com/CityScope/CSL_Paris/issues/16#issuecomment-612246617)
> I've tested Tri's OBJ and it rendered the cultural objs in odd diagonal.

The odd diagonal is not the Champs Elysées it looks the same as on qgis
<img width="708" alt="Screen Shot 2020-04-11 at 01 26 11" src="https://user-images.githubusercontent.com/3928502/79029161-79acd400-7b93-11ea-9624-e0b96066a515.png">

**Comment by tnguyenh** [comment]
It should be ok now... let me know if it does not work. Have fun :)

**Comment by agrignard** [comment]
I close this issue as it has drifted from its initial issue (z-fighting which is fixed see #18 for more information)
