### ISSUE TITLE
Problem when pressing F5 in the virtual room

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#22]
To reproduce

````
Run npm start 
Enter ones in the virtual room 
Press F5
````

On my browser (chrome Version 80.0.3987.163 (Official Build) (64-bit)) this is what I have after pressing F5. Then even if I rerun npm start i always get this page. I need to close the tabs and redo npm start.

<img width="1897" alt="Screen Shot 2020-04-10 at 12 40 40" src="https://user-images.githubusercontent.com/3928502/78985325-c7d8bd80-7b28-11ea-9667-d65909ea5a8a.png">

**Comment by RELNO** [comment]
cannot reproduce but try 18c875fcf248e707b9f72cd54eb3f841bd740beb and LMK

**Comment by agrignard** [comment]
Ok fix with this commit
