### ISSUE TITLE
Deploy Virtual Champs on a website

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#26]
To start the test with different people, what about deploying it so we can give link to the more people to have their feedback?

@RELNO how difficult is it to point this GitHub to the virtual experiment?

**Comment by RELNO** [comment]
a placeholder `gh-pages` now exist. Please make sure not to remove it as I test ML subdomain redirecting.

**Comment by agrignard** [comment]
What is the temporal url ? So that they can integrate it in the webste and test? Then they will change (can be done later) to the final url

**Comment by RELNO** [comment]
http://rechamp.media.mit.edu/

**Comment by agrignard** [comment]
It's not the same version as the current master isn't it?

**Comment by agrignard** [comment]
> a placeholder `gh-pages` now exist. Please make sure not to remove it as I test ML subdomain redirecting.

How do I access to the gh-pages? I guess it's in the branch https://github.com/CityScope/CSL_Paris/tree/gh-pages but how do we access it from outside with a simple url?

**Comment by agrignard** [comment]
I cannot access to the cityscope table on the current version of this
http://rechamp.media.mit.edu/

It stays on the first page
