### ISSUE TITLE
Color Schema

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#27]
To make the table more readable (and to keep the initial designed that also has a kind of french touch)

I would replace the green color for bike by blue. Now Park and bike are the same color

Then for the cultural white was used (it should pop up pretty well on the 3D model which is more gray)

**Comment by RELNO** [comment]
![Screen Shot 2020-04-18 at 14 22 00](https://user-images.githubusercontent.com/14296774/79670061-30114a00-818e-11ea-927e-01f025a4ea6f.png)

White does not work well, even when the city model was reduced to 30% 
I'd suggest to use these for now 
![Screen Shot 2020-04-18 at 16 04 25](https://user-images.githubusercontent.com/14296774/79670070-49b29180-818e-11ea-9997-bab960002ebd.png)

**Comment by agrignard** [comment]
Good joke the pink but no way!

**Comment by RELNO** [comment]
you'll get use to that, trust me!

**Comment by agrignard** [comment]
Are you sure you're not using some alpha?  iI see this in the code
````
#FFF7
``````

the white of the pedestrain is white isn't it?

**Comment by agrignard** [comment]
No I am serious there won't be any pink in this project;-)

**Comment by RELNO** [comment]
> Are you sure you're not using some alpha? iI see this in the code

no. #fff7 is just the button color.

**Comment by agrignard** [comment]
mm I see but the white pedestrian is pretty white no?

**Comment by RELNO** [comment]
the peds are practically GL lights, so it's different rendering. If we go with white light on the cultural buildings, it will be flat like this 
![image](https://user-images.githubusercontent.com/14296774/79670369-5d5ef780-8190-11ea-8407-818f2048a651.png)

**Comment by agrignard** [comment]
<img width="194" alt="Screen Shot 2020-04-20 at 11 30 31" src="https://user-images.githubusercontent.com/3928502/79737016-fd389480-82fa-11ea-8f1a-ecf33adb1abe.png">
Ccolor of the pedestrian needs  to be white in the legend (kind of french flag).

Can we make a try in white for the cultural and change it in the legend and on the display. As cultural attracks pedestrain (they are the one that stops there is the simulaltion it's necessary to have the culural the same color as the pedestrian)

**Comment by agrignard** [comment]
Are we converging on this? I see some iteration made on the radar with some colors related to this scheme, which cannot be the final one

**Comment by agrignard** [comment]
OK i don't see the point of arguing alone here

**Comment by RELNO** [comment]
@agrignard if you clone this one https://github.com/CityScope/CSL_Paris/blob/a33d24ca68448e57815719d551b1a260102d6ee4/champscope/src/settings.json
you can test the white version -- I don't mind which color we end up with, but white disappears in the ~gray b/g

**Comment by agrignard** [comment]
I tried with this settings.json
it's a blue version no?
<img width="937" alt="Screen Shot 2020-04-22 at 22 06 56" src="https://user-images.githubusercontent.com/3928502/80028593-a3e08900-84e5-11ea-8cd9-5f581d0385b1.png">

**Comment by RELNO** [comment]
sorry, yes -- change to:

``` 

 "cultural_before": {
            "URL": "resources/model/culture/culture_before.obj",
            "color": "(200, 0%, 70%)",
            "position": [0.3, 0.695, 0.08],
            "scale": 0.0355
        },
        "cultural_after": {
            "URL": "resources/model/culture/culture_after.obj",
            "color": "(200, 0%, 90%)",
            "position": [0.3, 0.69, 0.08],
            "scale": 0.0355
        }

```

**Comment by agrignard** [comment]
Indeed the white is not white.
