### ISSUE TITLE
Agents 'explode' on init 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#28]
in last version of sim, certain agents (most visible with pedestrians) have unrealistic behavior of aggregation and 'explosion'. since it's very short sim, agents should spawn from the middle of their trips.

**Comment by RELNO** [comment]
@agrignard is there an updated sim file?

**Comment by agrignard** [comment]
Yes I wil udpate it

**Comment by agrignard** [comment]
fixed in https://github.com/CityScope/CSL_Paris/commit/4688bfa0edc896dcd4a872e92cbbdd99066ed528
