### ISSUE TITLE
Model Spatial calibration 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#3]
Does having the lat,long of the 4 corners can help to calibrate? 

This file represents the table bounds

https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/includes/GIS/TableBounds.shp

The explosion concept why not but it seems that we don't have a proper way to match the 3D. Maybe the rotation is introducing some difficulty to map it?

**Comment by agrignard** [comment]
There is still a slight misalignment between the different layer. The agent are supposed to be in the middle of the champ for instance

<img width="1125" alt="Screen Shot 2020-04-07 at 09 51 22" src="https://user-images.githubusercontent.com/3928502/78643944-5e9d4400-78b5-11ea-833e-b5304c44cb8d.png">

**Comment by RELNO** [comment]
closing this in favor of focusing #18
