### ISSUE TITLE
Select camera position in POIs 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#30]
Have a selector for different views. @agrignard what are the 3-5 most important POIs to focus to?

**Comment by RELNO** [comment]
One view should be top/plan view

**Comment by agrignard** [comment]
I would say
arc de triomphe
<img width="997" alt="Screen Shot 2020-04-15 at 16 02 52" src="https://user-images.githubusercontent.com/3928502/79346460-b3366400-7f32-11ea-9251-4253bea20bd8.png">
One part of the ChampsElysées street
<img width="1199" alt="Screen Shot 2020-04-15 at 16 03 02" src="https://user-images.githubusercontent.com/3928502/79346488-bc273580-7f32-11ea-9498-a87d25936eec.png">
between Grand and Petit Palais
<img width="1196" alt="Screen Shot 2020-04-15 at 16 03 13" src="https://user-images.githubusercontent.com/3928502/79346516-c34e4380-7f32-11ea-8ace-af6c55a76903.png">
and place de la concorde
<img width="595" alt="Screen Shot 2020-04-15 at 16 03 31" src="https://user-images.githubusercontent.com/3928502/79346544-ce08d880-7f32-11ea-90b4-b4fddd7e3073.png">
and maybe a view like this 
<img width="1101" alt="Screen Shot 2020-04-15 at 16 04 53" src="https://user-images.githubusercontent.com/3928502/79346616-df51e500-7f32-11ea-844c-0e62a33f87c3.png">

**Comment by agrignard** [comment]
and what could be great but i guess it's more work is to propsoe a "journey" with an animated cam that goes from POIs to POIS

**Comment by agrignard** [comment]
Problem with Some point of"Avenues Champs Elysées" and "Place de la Concorde" point of view comapre to what has been proposed

Champs Elysées (the goal is to see at the level of the street what is the impact)
<img width="1623" alt="Screen Shot 2020-04-21 at 16 55 54" src="https://user-images.githubusercontent.com/3928502/79881085-158adb00-83f1-11ea-9f2c-5ecf884d2d77.png">
Concorde (to see the change especially in number of lines and people on the place)
<img width="1342" alt="Screen Shot 2020-04-21 at 16 58 04" src="https://user-images.githubusercontent.com/3928502/79881329-5551c280-83f1-11ea-8694-6d35c0a33704.png">

**Comment by agrignard** [comment]
Concorde from the top
Grand Palais north facing

**Comment by RELNO** [comment]
I think we've fixed that by now. open if still an issue.
