### ISSUE TITLE
Disable rotating camera in settings

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#34]
Having a button (as it was before) to disable to camera rotation (it's good to keep it by default by quickly the user will want to use the cam). Right now ones need to select one of the scene to then be able to use the cam

**Comment by RELNO** [comment]
closed @ https://github.com/CityScope/CSL_Paris/commit/dd09786689125a6202e1c58a3311f808b316573c

**Comment by agrignard** [comment]
I can see the animate camera button but it doesn't seem to work on mine

<img width="257" alt="Screen Shot 2020-04-21 at 10 23 12" src="https://user-images.githubusercontent.com/3928502/79843187-35eb7300-83ba-11ea-85db-0e86c1c78b97.png">

**Comment by RELNO** [comment]
I'll leave it now with the current options, LMK if this is a problem
