### ISSUE TITLE
Issue in the Radar Spike related to cars

### ISSUE THREAD

**Issue by LAAP** [CityScope/CSL_Paris#38]
@nayoub and @agrignard 

I have realised that there is a modification in the radar related to the Spike of the cars. Basically it doesn't change form 2020 to 2040. In my radar made in Lyon, it was like this:

![200130_Radar_Urban_Indicators_Champs_Elise_R](https://user-images.githubusercontent.com/19315213/79812299-845f2a00-8346-11ea-8cf2-9958aff1b43e.jpg)

And now, it is like this:

![200130_Radar_Urban_Indicators_Champs_Elise_R2](https://user-images.githubusercontent.com/19315213/79812315-8fb25580-8346-11ea-93ef-ed38a6654106.jpg)

Please, let me know your thoughts

**Comment by agrignard** [comment]
@LAAP I don't think you are lokking at the radar that are displayed in the exhibition.

The last and only one (that were indeed modify as there was this error are this one) 
<img width="1651" alt="Screen Shot 2020-04-21 at 10 31 42" src="https://user-images.githubusercontent.com/3928502/79844026-6849a000-83bb-11ea-8e95-3681d8fceb0e.png">
<img width="1653" alt="Screen Shot 2020-04-21 at 10 31 36" src="https://user-images.githubusercontent.com/3928502/79844063-73043500-83bb-11ea-9bd9-973174094704.png">
That can be found on the github here 
https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/includes/PNG/radar_plot/radar_plot.001.jpeg
and
https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/includes/PNG/radar_plot/radar_plot.002.jpeg

**Comment by LAAP** [comment]
Hi @agrignard , That is the french version, the English version is in:

https://github.com/CityScope/CSL_Paris/blob/master/champscope/public/resources/textures/radar/Radar_Plot_EN.ai

And it has this spike issue that I am mentioning 

@nayoub , please, can you help me with it?

**Comment by nayoub** [comment]
Yes I took the wrong version, so sorry.
I just pushed the good one (Radar_Plot_EN_Expo.ai)

**Comment by LAAP** [comment]
Ok. Thank you @nayoub 
Now I am closing this issue
