### ISSUE TITLE
Virtual CityScope Interface

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#4]
To reproduce what we have in the pavillon here are the principal parameter/toggle.

The simulation is made of 2 main modes: Paris Now and Paris in 2030. 
For each mode we have a simulation representing: 

- people, bike and car for "moving dot"
- Park and Cultural places for static building (they are basically more park and more cultural building in the future)

Then the road are represented thanks to the trace produced by the agent, showing then a kind of emerging network, this was one of the big part fo the implentation to be able to generate nice trace from the position of the agent but let's see how it looks with the built-in three.js

In term of visualization we need then to be able to differentiate the following layers:

- Moving dot (with trace)
1. people
2. bike
3. car 
- Static Polygon
1. park 
2. Cultural places 

In term of interface, (could be cool to reproduce the one in the pavillon) There is basically 5 buttons
- One to trigger people and bike
- One to trigger before/after
- One to trigger car
- One to trigger park
- One to trigger cultural spaces

@nayoub can you push the 3D model of the interface, to see how to load it in the 3D world?

<img width="769" alt="Screen Shot 2020-03-29 at 20 45 43" src="https://user-images.githubusercontent.com/3928502/77857527-53378200-71fe-11ea-9d31-230446b2f392.png">

**Comment by agrignard** [comment]
For the moving dot @RELNO is it ok for you if we have 6 files:

people_now.json
bike_now.json
car_now.json

people_future.json
bike_future.json
car_future.json

**Comment by RELNO** [comment]
- We'll implement the interface as UI on top of the screen, so no need for 3d model of this. 
- 6 files are doable, but then it's x6 loaders / parsers passes. Can you produce 1 file for each scenario?

**Comment by nayoub** [comment]
Sure, do you need a vector or raster file for the UI?

**Comment by RELNO** [comment]
@nayoub not really, it will be done via simple HTML5 buttons

**Comment by agrignard** [comment]
> * We'll implement the interface as UI on top of the screen, so no need for 3d model of this.
> * 6 files are doable, but then it's x6 loaders / parsers passes. Can you produce 1 file for each scenario?

If it's ok for you I think it will be more generic to have separate files, like you can almost see it as layers that will be activated or not thanks to the buttons, each file would be used to instantiate the agent corresponding to the layer. It might be a longer at the beginning to implement but much more flexible in the long run I think.

**Comment by RELNO** [comment]
ok -- we can try split flies, let's see later if it creates serious overhead. For now, let's focus on #5 since I think it might be more challenging

**Comment by LAAP** [comment]
@agrignard Arnaud said that "To reproduce what we have in the pavillon" we need... Can we do things a bit different in the virtual world? Maybe we can have the "same thing than in Parish", + maybe trying to integrate more "exploration of the lawyers" (e.g. the Radar, the separate lawyers, some numbers from the simulation... )

**Comment by agrignard** [comment]
Sure as soon as the initial copy is finished we can make it better even;-) THough I personally thing the exercise here is to reproduce a physical space that already exists but sure we can take some freedom

**Comment by agrignard** [comment]
The interface is the following:

You have **one button that make you switch before and after** and then you **toogle on/off the display of the car, bike, pedestrain, park and cultural**.

I am not sure exactly what the current interface is doing. It looks like the toggle is for before and after for all of them, it should be on and off expect for the 2020/2040. As it is you can go in a weird configuration where you think you are in 2040 but you put all the layer to 2020.


<img width="958" alt="Screen Shot 2020-04-10 at 12 23 41" src="https://user-images.githubusercontent.com/3928502/78984289-31a39800-7b26-11ea-9429-d50c244292d1.png">

**Comment by agrignard** [comment]
When triggering the interface I would keep it unless the user remove it. right now as soon as I click on the view (for instance to drag) the menu disapears

**Comment by agrignard** [comment]
This is fixed now, the toogle are doing the right thing. I close this issue to create more specific one if need
