### ISSUE TITLE
Don't merge to Master without PR

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#40]
All -- As asked before, **please do not merge to `master` without PRs**, at the very least not to `campscope` folder. PRs are the only way for me to see what changed and what might cause issues in other parts of the app that are not related to your push.

**Comment by agrignard** [comment]
I don't see it either as an issue nor as a bug (and I see it more as an issue to collaborate, you can always track change by looking at the commit isn't it instead of requesting a PR for each change).
