### ISSUE TITLE
Text typos and credits in the home page

### ISSUE THREAD

**Issue by nayoub** [CityScope/CSL_Paris#41]
I imagine that the text is not final but I noticed some typos, corrected below:

> CityScope Champs-Élysée**s** is a Tangible User Interface for urban planning and decision-making, that was installed as part of an exhibition in **the** Pavillon de l'Arsenal, Paris. The exhibition by PCA-STREAM explored new plans and future interventions for Champs Élysées **Avenue**. These include reduced traffic, encouraged walkability, cycling and pedestrian movement **on** the famous street. As well, the project suggested improved access to cultural landmarks and amenities along the **Avenue**. Due to **COVID-19**, we have decided to move this exhibition online. This website **allows** users to explore MIT CityScope Champs-Élysée**s** in an interactive and immersive way.
**Exhibition** in Pavillon de l'Arsenal
>

**Comment by RELNO** [comment]
@nayoub thanks

**Comment by agrignard** [comment]
Exh**a**bition in Pavillon de l'Arsenal -> Exh**i**bition

Also the credits in the home page should be updated with the same one as the one if the information of the virtual CityScope (I don't think we should mention PCA) and the cityscope is developped by and Gama is developed by doesn't have to appear on the main page it will be too long


<img width="538" alt="Screen Shot 2020-04-22 at 22 44 57" src="https://user-images.githubusercontent.com/3928502/80032092-f1abc000-84ea-11ea-8d38-804904d6b662.png">
