### ISSUE TITLE
pedestrian simulation is fixed in some point  (0,0 ?) 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#44]
<img width="196" alt="Screen Shot 2020-04-26 at 18 29 02" src="https://user-images.githubusercontent.com/14296774/80321553-df33ce00-87eb-11ea-9090-f56dd035cef7.png">

looks like some agents are stuck outside the table area

**Comment by agrignard** [comment]
very weird... isn't it related to #36 ? It appears only during the first round on the simulation then it disappears ones the first simualtion is finished, I don't think it's in the json file

**Comment by RELNO** [comment]
I guess it's a won't fixed bug. closing
