### ISSUE TITLE
Export Building in a geojson but with GAMA coordinate

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#6]
In order to feed the WebGL simulation we need to store in a json (geojson) the parks and cultural so that it can be displayed.

So far the location of the agent this is what has been done in GAMA, first a transformation in WGS84, then a conversion in the GAMA world and then a scaling by 2000 to fit the "real world" , by real world I mean the table is 1/2000 scale.
`````
point loc<-CRS_transform(l, "EPSG:4326").location;				
loc<-point(to_GAMA_CRS(loc, "EPSG:4326"))/2000;
`````

I'd like to do the same for the parks and the cultural by using this kind of export in Save to GeoJson
`````
save building to:"../results/buildings.geojson" type: "json";
``````

However by doing that the value will be in a projected value (WGS_84) , is it possible to have the equivalent of the ````to_GAMA_CRS````operator for the ````save````

**Comment by ptaillandier** [comment]
Can you test to just use something like this?
save pedestrian to: "pedestrian.geojson" type:json crs: "EPSG::2154";
save building to: "building.geojson" type:json crs: "EPSG::2154";

**Comment by agrignard** [comment]
This work in the sense that it create it in the Lambert projection butthis is not waht I am looking for. i'd like to have them in the GAMA world (the world that goes from {0,0} to {world.Shape.width (=more less 3000m);world.shape.height(more or less 2000m)} like what to_GAMA_CRS is doing

**Comment by ptaillandier** [comment]
Ok, you can update GAMA and test:
save pedestrian to: "pedestrian.geojson" type:json crs: "GAMA";
save building to: "building.geojson" type:json crs: "GAMA";

**Comment by agrignard** [comment]
Thank you @ptaillandier it's working on the  Gama Git version.

@RELNO I'll produce a park_before.geojson, park_after_geojson, cultural_before.geosjon, cultural_after.geojson

**Comment by agrignard** [comment]
Ok the 4 files have been generated.

In the same mood as the agent they are in the right scale they just need to be rotated and translated like this

So it's basically parcing a geojson file and creating a polygon for each of them (I guess three.js as some native geojson parser?)

`````
    agentsWrapper.rotation.set(0, 0.4625123, 0);

    agentsWrapper.position.set(
        -(Math.cos(0.4625123) * 822) / 2000 - 1.57 / 2,
        0,
        (Math.sin(0.4625123) * 822) / 2000 - 0.92 / 2
    );
`````

**Comment by RELNO** [comment]
I'm not sure what's the purpose of exporting shp => geojson. threejs has no native way to parse geojson, and in any case the city 3d model was parsed via qgis =>blender=> json (note, this is 3d json, not geojson). 
If you want to try, there are some attempts to convert geojson to threejs: https://observablehq.com/@mbostock/geojson-in-three-js

**Comment by agrignard** [comment]
The goal is to avoid using QGIS and Blender the data are already here in the right coordinate referential (like the agents)

I can also export them as .shp file to make the QGIS/Blender pipe?

I'll have a look at the geojson in Three.js

**Comment by agrignard** [comment]
.shp pushed here
https://github.com/CityScope/CSL_Paris/tree/master/champscope/GIS/Champ_GIS_buildings

**Comment by RELNO** [comment]
> The goal is to avoid using QGIS and Blender the data are already here in the right coordinate referential (like the agents)

See my comment on #9, unlike the parks, the agents are not geojson.

> .shp pushed here
https://github.com/CityScope/CSL_Paris/tree/master/champscope/GIS/Champ_GIS_buildings

Thanks

**Comment by RELNO** [comment]
@agrignard maybe to save you some time: if you still want to parse your own geojsons, this guy did a first step https://codesandbox.io/s/geojson-to-3d-test-g24uy 
But it might be a different story for irregular shapes & convexes

**Comment by agrignard** [comment]
I close this issue as the export is done now the remaining part is to display them see #9

**Comment by agrignard** [comment]
@ptaillandier the export now is working and creating a list of polygon in the geojson

I was wondering is it possible (I guess by creating a new geometry in GAMA that will aggregate all the building) to export it as one Multypolygon made of N coordinates list instead of N Polygon made of one coordinates list.

This is just in order to be compatible with another library that is waiting a multipolygon instead of N polygon

**Comment by ptaillandier** [comment]
You can try to make a union of all geometries
geometry big_geom <- union(building collect each.shape);

**Comment by agrignard** [comment]
it's seems to create the good geometry but then 

`````
save big_geom to:"./results/parks_before.geojson" type:"json" crs:"GAMA::"+scale;
`````

doesn"t work (it compiles but doesn't create the file)

**Comment by ptaillandier** [comment]
Why do you mean?
Because I tested this simple model  (with your building data) and it works (at least, a file is created):
```
model NewModel1

global {
	shape_file bd_shape <- shape_file("../includes/buildings.shp");
	geometry shape <- envelope(bd_shape);
	init {
		create building from: bd_shape;
		float scale <- 1/1000.0;
		
		save union(building) to: "building_test.geojson" type:json crs: "GAMA::" + scale;
	
	}
}

species building;

experiment NewModel1 type: gui ;

```

**Comment by ptaillandier** [comment]
Why do you mean?
Because I tested this simple model  (with your building data) and it works
(at least, a file is created):
```
model NewModel1

global {
shape_file bd_shape <- shape_file("../includes/buildings.shp");
geometry shape <- envelope(bd_shape);
init {
create building from: bd_shape;
float scale <- 1/1000.0;

save union(building) to: "building_test.geojson" type:json crs: "GAMA::" +
scale;

}
}

species building;

experiment NewModel1 type: gui ;

```

Le jeu. 2 avr. 2020 à 15:13, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Yes it works. Thank you!
