### ISSUE TITLE
Display Park and Cultural before and after Geojson in WebGL

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#9]
Ok the 4 files have been generated here
https://github.com/CityScope/CSL_Paris/tree/master/champscope/GIS/park_cultural

In the same way as the agent have been produced they are in the right scale they just need to be rotated and translated like this
`````
    agentsWrapper.rotation.set(0, 0.4625123, 0);

    agentsWrapper.position.set(
        -(Math.cos(0.4625123) * 822) / 2000 - 1.57 / 2,
        0,
        (Math.sin(0.4625123) * 822) / 2000 - 0.92 / 2
    );
`````

So it's basically parcing a geojson file and creating a polygon for each of them.

 I guess some native geojson parser in three.js will do the jib however I am not sure a classical library would work as here it's a bit a workaround, it's using a Geojson format but the data are not in a specific projection.

**Comment by RELNO** [comment]
As mentioned in #6, there's no simple way to work with geojson in three. The agents are not geojson, but only a cluster of points with no relations between them.

**Comment by agrignard** [comment]
Yep the geojson is just a way to store the geometry that can also be seen as a list of non related polygon

**Comment by agrignard** [comment]
See
https://codesandbox.io/s/geojson-to-3d-test-g24uy
and 
https://observablehq.com/@mbostock/geojson-in-three-js

**Comment by agrignard** [comment]
I made an attempt here https://github.com/CityScope/CSL_Paris/commit/ba34f69705db425aed509d0855c78dca49e32a5b to integrate this code https://codesandbox.io/s/geojson-to-3d-test-g24uy but I am missing , something...

Seems to compile but not sure if the elements are really added to the scene.

I created a ThreeScene_Test_Arnaud.js to debug it

**Comment by agrignard** [comment]
So 2 things here 

1. parks_before.geojson is not exactly the same format as the cityTest.geojson (Polygon vs MultiPolygon) so the building are actually not added to the scene
2. however even when trying to display the cityTest.geojson (just change the file name) I cannot see them either

**Comment by agrignard** [comment]
Won't be adressed in this version
